// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYvRgCyvVJylFvxaJNPqSc4rOcRg95tIU',
    appId: '1:370951174156:web:2656d4ef4cf709ae299629',
    messagingSenderId: '370951174156',
    projectId: 'perpustakaan-smkn8-app',
    authDomain: 'perpustakaan-smkn8-app.firebaseapp.com',
    storageBucket: 'perpustakaan-smkn8-app.appspot.com',
    measurementId: 'G-S6CMFN3DLF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfBoCYQMHA8vNvfIk60T7LcXX95Ot_yaI',
    appId: '1:370951174156:android:ddfd3659dd76061b299629',
    messagingSenderId: '370951174156',
    projectId: 'perpustakaan-smkn8-app',
    storageBucket: 'perpustakaan-smkn8-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiPFzRvYpFR8l9wLruMyIHNdqtcAF_6l8',
    appId: '1:370951174156:ios:4507c390bada251c299629',
    messagingSenderId: '370951174156',
    projectId: 'perpustakaan-smkn8-app',
    storageBucket: 'perpustakaan-smkn8-app.appspot.com',
    iosClientId: '370951174156-j9ub9cfkqtdjpgca4ett4ll7tbgs8uon.apps.googleusercontent.com',
    iosBundleId: 'com.rifara.smkn8kotatangerang.perpustakaanSmkn8KotaTangerang',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiPFzRvYpFR8l9wLruMyIHNdqtcAF_6l8',
    appId: '1:370951174156:ios:4507c390bada251c299629',
    messagingSenderId: '370951174156',
    projectId: 'perpustakaan-smkn8-app',
    storageBucket: 'perpustakaan-smkn8-app.appspot.com',
    iosClientId: '370951174156-j9ub9cfkqtdjpgca4ett4ll7tbgs8uon.apps.googleusercontent.com',
    iosBundleId: 'com.rifara.smkn8kotatangerang.perpustakaanSmkn8KotaTangerang',
  );
}
